openapi: 3.0.1
info:
  title: pdfsigner
  version: '1.0'
servers:
  - url: /
security:
  - default: []
paths:
  /:
    post:
      tags: [pdf]
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
                - pdf
                - pkcs12
                - options
              type: object
              properties:
                pdf:
                  type: string
                  description: >-
                    Archivo PDF a ser firmado
                  format: binary
                pkcs12:
                  type: string
                  description: >-
                    Archivo contenedor de llaves con formato PKCS12 y con MIME type
                    `application/pkcs12` o `application/x-pkcs12`
                  format: binary
                signatureImage:
                  type: string
                  description: >-
                    Archivo de imagen con MIME type `image/*` a mostrar en la
                    la firma digital
                  format: binary
                options:
                  type: string
                  description: >- 
                    Archivo con MIME type `application/json` con las siguientes opciones:
                    
                    ```
                    
                    {
                      "pkcs12FilePassword": "string",
                      "signerEntity?": "string",
                      "signerJobTitle?": "string",
                      "signatureWidth?": number,
                      "signatureHeight?": number.
                      "signaturePositionX?": number,
                      "signaturePositionY?": number,
                      "signatureDescription?": "string",
                      "signatureImageSize?": number,
                      "signatureImageRelativePositionX?": number,
                      "signatureImageRelativePositionY?": number.
                      "signatureDescriptionRelativePositionX?": number,
                      "signatureDescriptionRelativePositionY?": number,
                      "signatureFontSize": number
                    }
                    
                    ```
                    
                    `pkcs12FilePassword` contiene la clave del fichero en el p치metro `pkcs12` y es requerido.<br>
                    `signerEntity` es opcional e identifica a la entidad a la cual pertenece la persona que firma.<br>
                    `signerJobTitle` es opcional y contiene el cargo que ocupa la persona que firma.<br>
                    `signatureWidth` es opcional y contiene el ancho del rectangulo de la firma.<br>
                    `signatureHeight` es opcional y contiene el alto del rectangulo de la firma.<br>
                    `signaturePositionX` es opcional y contiene la coordenada `x` de la esquina superior izquierda del rectangulo de la firma.<br>
                    `signaturePositionY` es opcional y contiene la coordenada `y` de la esquina superior izquierda del rectangulo de la firma.<br>
                    `signatureDescription` es opcional y contiene el texto visible de la firma, admite formato markdown.<br>
                    `signatureImageSize` es opcional y contiene el tamanio de la imagen a poner en la firma.<br>
                    `signatureImageRelativePositionX` es opcional y contiene la coordenada `x` de la esquina superior izquierda de la imagen dentro del rectangulo de la firma.<br>
                    `signatureImageRelativePositionY` es opcional y contiene la coordenada `y` de la esquina superior izquierda de la imagen dentro del rectangulo de la firma.<br>
                    `signatureDescriptionRelativePositionX` es opcional y contiene la coordenada `x` de la esquina superior izquierda de la descripcion dentro del rectangulo de la firma.<br>
                    `signatureDescriptionRelativePositionY` es opcional y contiene la coordenada `y` de la esquina superior izquierda de la descripcion dentro del rectangulo de la firma.<br>
                    `signatureFontSize` es opcional y contiene el tamanio de letra a usar en el texto de la firma.

                  format: binary
        required: true
      responses:
        '200':
          description: OK
          content:
            application/pdf:
              schema:
                type: string
                format: binary
          headers:
            Content-Disposition:
              schema:
                type: string
                description: Used only with `application/pdf` responses
                example: attachment; filename="name.pdf"
        '400':
          description: Bad Request
      security:
        - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
  /validate-pdf:
    post:
      tags: [pdf]
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
                - pdf
              type: object
              properties:
                pdf:
                  type: string
                  description: >-
                    Archivo PDF a ser validado
                  format: binary
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PdfValidationResponse"
        '400':
          description: Bad Request
      security:
        - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
  /validate-pkcs12:
    post:
      tags: [pkcs12]
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
                - pkcs12
                - password
              type: object
              properties:
                pkcs12:
                  type: string
                  description: >-
                    Archivo contenedor de llaves con formato PKCS12 y con MIME type
                    `application/pkcs12` o `application/x-pkcs12`
                  format: binary
                password:
                  type: string
                  description: >-
                    Contiene la clave del fichero en el p치metro `pkcs12`
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pkcs12ValidationResponse"
        '400':
          description: Bad Request
      security:
        - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
  /parse-pkcs12:
    post:
      tags: [pkcs12]
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
                - pkcs12
                - password
              type: object
              properties:
                pkcs12:
                  type: string
                  description: >-
                    Archivo contenedor de llaves con formato PKCS12 y con MIME type
                    `application/pkcs12` o `application/x-pkcs12`
                  format: binary
                password:
                  type: string
                  description: >-
                    Contiene la clave del fichero en el p치metro `pkcs12`
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pkcs12ParseResponse"
        '400':
          description: Bad Request
      security:
        - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
  /change-pkcs12-password:
    post:
      tags: [pkcs12]
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
                - pkcs12
                - oldPassword
                - newPassword
              type: object
              properties:
                pkcs12:
                  type: string
                  description: >-
                    Archivo contenedor de llaves con formato PKCS12 y con MIME type
                    `application/pkcs12` o `application/x-pkcs12`
                  format: binary
                oldPassword:
                  type: string
                  description: >-
                    Contiene la clave del fichero en el p치metro `pkcs12`
                newPassword:
                  type: string
                  description: >-
                    Contiene la clave final del `pkcs12` resultante
        required: true
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
components:
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://test.com'
          scopes: {}
  schemas:
    PdfValidationResponse:
      type: object
      properties:
        isValid:
          type: boolean
        hasWarnings:
          type: boolean
        verifiedAt:
          type: string
          format: date-time
        signatures:
          type: array
          items:
            $ref: "#/components/schemas/PdfSignatureValidationResult"
    PdfSignatureValidationResult:
      type: object
      properties:
        name:
          type: string
        isValid:
          type: boolean
        signedAt:
          type: string
          format: date-time
        caChain:
          type: array
          items:
            type: string
        errors:
          type: array
          items:
            type: string
        warnings:
          type: array
          items:
            type: string
        infoMessages:
          type: array
          items:
            type: string
    Pkcs12ValidationResponse:
      type: object
      properties:
        isValid:
          type: boolean
        message:
          type: string
    Pkcs12ParseResponse:
      type: object
      properties:
        isValid:
          type: boolean
        message:
          type: string
        notBefore:
          type: string
          format: date-time
        notAfter:
          type: string
          format: date-time
        subject:
          type: string
        issuer:
          type: string
x-wso2-auth-header: Authorization
x-wso2-cors:
  corsConfigurationEnabled: true
  accessControlAllowOrigins:
    - '*'
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
    - authorization
    - Access-Control-Allow-Origin
    - Content-Type
    - SOAPAction
    - apikey
    - testKey
  accessControlAllowMethods:
    - GET
    - PUT
    - POST
    - DELETE
    - PATCH
    - OPTIONS
x-wso2-production-endpoints:
  urls:
    - 'http://pdfsigner.cubaface.svc.cluster.local:8080'
  type: http
x-wso2-sandbox-endpoints:
  urls:
    - 'http://pdfsigner.cubaface.svc.cluster.local:8080'
  type: http
x-wso2-basePath: /pdfsigner/1.0
x-wso2-transports:
  - https
x-wso2-response-cache:
  enabled: false
  cacheTimeoutInSeconds: 300
